/* SPDX-License-Identifier: GPL-2.0-only */
/*
 * Copyright (c) 2016-2017, The Linux Foundation. All rights reserved.
 * Copyright (c) Qualcomm Technologies, Inc. and/or its subsidiaries.
 */
#ifndef __HAB_GRANTABLE_H
#define __HAB_GRANTABLE_H

/* Grantable should be common between exporter and importer */
struct grantable {
	unsigned long pfn;
};

struct compressed_pfns {
	unsigned long first_pfn;
	int nregions;
	struct region {
		int size;
		int space;
	} region[];
};

struct lb_mem_info {
	uint32_t origin_exp_id; /* export id originally generated by remote HAB */
	int origin_mmid; /* MMID where the memory was exported in remote HAB */
	uint32_t reserved;
};

struct mem_share_metadata {
	union {
		struct compressed_pfns pfns;
		struct lb_mem_info lb_mem;
	};
};
#endif /* __HAB_GRANTABLE_H */
